### ISSUE TITLE
Resolve the error while signIn and login.

### ISSUE THREAD

**Issue by deep1296** [haseeb1233/cruel-scale-8764#15]
- [ ] 
<img width="938" alt="image" src="https://github.com/haseeb1233/cruel-scale-8764/assets/96063026/ead85bb4-4020-4dd1-a8ae-738342fd751e">

- [ ] 
<img width="936" alt="image" src="https://github.com/haseeb1233/cruel-scale-8764/assets/96063026/44b75f78-7102-40ce-ae2f-fb3ab8575752">

**Comment by Shubham-Pilane** [comment]
completed the login and signup part please review it
